name: CD

on:
  push:
    branches: [ release ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Login to Public ECR
        run: |
          aws ecr-public get-login-password --region us-east-1 \
          | docker login --username AWS --password-stdin public.ecr.aws

      - name: Build Docker image
        run: |
          # '.' 대신 './discodeit'으로 경로를 지정합니다.
          # 이렇게 하면 도커가 discodeit 폴더 안의 Dockerfile을 찾아 빌드합니다.
          docker build -t ${{ vars.ECR_REPOSITORY_URI }}:latest ./discodeit
          docker tag ${{ vars.ECR_REPOSITORY_URI }}:latest ${{ vars.ECR_REPOSITORY_URI }}:${{ github.sha }}

      - name: Push Docker image
        run: |
          docker push ${{ vars.ECR_REPOSITORY_URI }}:latest
          docker push ${{ vars.ECR_REPOSITORY_URI }}:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Download task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition ${{ vars.ECS_TASK_DEFINITION }} \
            --query taskDefinition > task-def.json

      - name: Update task definition (image)
        run: |
          sed -i 's|public.ecr.aws/q1l1t8u5/discodeit:.*|${{ vars.ECR_REPOSITORY_URI }}:${{ github.sha }}|g' task-def.json

      - name: Register new task definition
        run: |
          aws ecs register-task-definition \
            --cli-input-json file://task-def.json

      - name: Stop existing ECS service (프리티어 메모리 확보)
        run: |
          aws ecs update-service \
            --cluster ${{ vars.ECS_CLUSTER }} \
            --service ${{ vars.ECS_SERVICE }} \
            --desired-count 0

      - name: Wait for service to stop
        run: |
          aws ecs wait services-stable \
            --cluster ${{ vars.ECS_CLUSTER }} \
            --service ${{ vars.ECS_SERVICE }}

      - name: Update ECS service with new task (새 버전 배포)
        run: |
          aws ecs update-service \
            --cluster ${{ vars.ECS_CLUSTER }} \
            --service ${{ vars.ECS_SERVICE }} \
            --task-definition ${{ vars.ECS_TASK_DEFINITION }} \
            --desired-count 1